name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Clean up old Docker images on EC2
        run: |
          docker images --format "{{.Repository}} {{.ID}}" | grep "lohitintern/task-manager" | awk '{print $2}' | xargs -r docker rmi || true


      - name: Pull the latest Docker image
        run:  docker pull lohitintern/task-manager:latest

      - name: Stop the old container
      #temp something i wrote
        run: docker stop task-manager-app || true

      - name: Remove the old container
        run: docker rm task-manager-app || true
      
      - name: Run the new container
        run: docker run -d --name task-manager-app -p 8080:80 lohitintern/task-manager:latest