# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager:latest .

      - name: Push the docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest