name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build and Tag the Docker Image
    #     run: |
    #       docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager:latest .
    #       docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager:latest ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}

      - name: Run Trivy Scan
        id: trivy_scan
        run: |
          TRIVY_REPORT=$(trivy image --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --format table owasp/juice-shop:v12.0.0)
          
          echo "## Vulnerability Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "<pre><code>$TRIVY_REPORT</code></pre>" >> $GITHUB_STEP_SUMMARY
          
          if echo "$TRIVY_REPORT" | grep -q 'HIGH' || echo "$TRIVY_REPORT" | grep -q 'CRITICAL'; then
            echo "vulnerability_found=true" >> $GITHUB_OUTPUT
            echo "::warning::Critical vulnerabilities were found. The pipeline will fail after this step."
          else
            echo "vulnerability_found=false" >> $GITHUB_OUTPUT
            echo "No high or critical vulnerabilities were found."
          fi

      - name: Send Email Alert on Vulnerability
        if: ${{ steps.trivy_scan.outputs.vulnerability_found == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'CRITICAL VULNERABILITIES FOUND in ${{ github.repository }}'
          body: |
            The Trivy scan for the Docker image has failed due to high or critical vulnerabilities.

            Please check the workflow logs for a detailed report of the vulnerabilities.
            
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 'lohit.intern@gmail.com'
          from: 'GitHub Actions' 

      - name: Fail the pipeline if vulnerabilities were found
        if: ${{ steps.trivy_scan.outputs.vulnerability_found == 'true' }}
        run: |
          echo "Failing pipeline due to critical vulnerabilities."
          exit 1
      
      - name: Push the Docker Image to Docker Hub
        if: ${{ steps.trivy_scan.outputs.vulnerability_found == 'false' }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}
