name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # UNCOMMENT THIS STEP to build your actual image
      # - name: Build and Tag the Docker Image
      #   id: build
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager:latest .
      #     docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager:latest ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}

      - name: Scan image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.18.0 
        with:
          image-ref: 'vulnerables/web-dvwa'
          severity: 'HIGH,CRITICAL'
          exit-code: 1 # This will make the step fail if HIGH or CRITICAL vulns are found
          format: 'table'
          output: 'trivy-report.txt' # Save the report to a file
        # THIS IS THE KEY: It allows the workflow to continue even if this step fails.
        continue-on-error: true

      - name: Send Email Alert and Fail on Vulnerability
        # This condition checks if the scan itself failed for ANY reason (vulnerabilities OR operational errors).
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          # The "cat" command needs to be conditional to avoid failing the step if the file was not created.
          if [ -f "trivy-report.txt" ]; then
            REPORT_BODY=$(cat trivy-report.txt)
            REPORT_BODY="${REPORT_BODY//'%'/'%25'}"
            REPORT_BODY="${REPORT_BODY//$'\n'/'%0A'}"
            REPORT_BODY="${REPORT_BODY//$'\r'/'%0D'}"
            echo "REPORT_FOR_EMAIL=$REPORT_BODY" >> $GITHUB_ENV
            echo "::warning::Vulnerabilities found! Sending email alert..."
            # --- YOUR EMAIL ACTION GOES HERE ---
          else
            echo "::error::Trivy scan failed to complete. No report was generated. Check previous step logs for details."
          fi
          
          # This command ensures the pipeline fails if the previous step failed for any reason.
          exit 1

      - name: Push the Docker Image to Docker Hub
        # This 'if' condition checks that the scan step succeeded.
        if: steps.trivy_scan.outcome == 'success'
        run: |
          echo "No critical vulnerabilities found. Pushing image..."
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}