name: CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: task-manager
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # This step is now only for running subsequent AWS CLI commands if needed,
      # but it is good practice to keep it for environment setup.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Tag the Docker Image Locally
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          load: true

      - name: Scan image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.18.0 
        with:
          image-ref: '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest'
          severity: 'CRITICAL'
          exit-code: 1 
          continue-on-error: true

      - name: Send Email Alert on Vulnerability
        if: steps.trivy_scan.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'CRITICAL VULNERABILITIES FOUND in ${{ github.repository }}'
          body: |
            The Trivy scan has found vulnerabilities in your Docker image.
            
            The pipeline will now FAIL and the image will NOT be pushed.
            
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 'lohit.intern@gmail.com'
          from: 'GitHub Actions'

      - name: Fail the Pipeline if vulnerabilities found
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          echo "Failing pipeline due to critical vulnerabilities."
          exit 1

      # The corrected, final block for pushing the image
      - name: Push the Docker Image to ECR
        if: steps.trivy_scan.outcome == 'success'
        # The 'env' block below explicitly provides the credentials to this step,
        # which guarantees the AWS CLI will find them.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "No critical vulnerabilities found. Pushing image..."
          
          # Get a login password and pipe it directly to docker login
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
          
          # Now, push the images
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}