C:.
├───.vscode
└───src
    ├───app
    │   ├───core
    │   │   ├───components
    │   │   │   ├───common-header
    │   │   │   ├───common-sidebar
    │   │   │   ├───dynamic-redirect
    │   │   │   └───loader
    │   │   ├───guards
    │   │   ├───interceptors
    │   │   └───services
    │   ├───shared
    │   │   ├───components
    │   │   │   ├───activity-trail
    │   │   │   ├───approval-workflow
    │   │   │   │   └───demo
    │   │   │   ├───attachment
    │   │   │   ├───common-badge
    │   │   │   ├───common-card
    │   │   │   ├───common-tab
    │   │   │   ├───common-table
    │   │   │   ├───configurable-button
    │   │   │   ├───conversation-trail
    │   │   │   ├───countdown-timer
    │   │   │   ├───google-places-component
    │   │   │   ├───gst-verify
    │   │   │   ├───login-component
    │   │   │   ├───phone-otp-verification
    │   │   │   └───split-button
    │   │   ├───formly-components
    │   │   ├───pipes
    │   │   └───services
    │   └───wefab
    │       ├───customer
    │       │   ├───component
    │       │   │   ├───customer-header
    │       │   │   └───customer-sidebar
    │       │   ├───customer-onboarding
    │       │   ├───email-verification
    │       │   ├───login-component
    │       │   ├───order
    │       │   │   ├───order-details
    │       │   │   └───order-list
    │       │   ├───quotation
    │       │   │   ├───quotation-details
    │       │   │   └───quotation-list
    │       │   ├───rfq
    │       │   │   ├───ai-analysis-summary-pages
    │       │   │   ├───create-rfq
    │       │   │   ├───rfq-list
    │       │   │   ├───submitted-rfq
    │       │   │   └───technical-review-page
    │       │   └───styles
    │       ├───public-rfq-view
    │       │   ├───basic-details
    │       │   └───register-to-quote
    │       ├───supplier
    │       │   ├───dashboard
    │       │   │   └───supplier-dashboard
    │       │   ├───finder
    │       │   │   └───supplier-finder
    │       │   ├───help-section
    │       │   ├───onboarding
    │       │   │   ├───supplier-onboarding-combined
    │       │   │   ├───supplier-onboarding-welcome-component
    │       │   │   └───supplier-profile-review
    │       │   ├───order
    │       │   │   ├───supplier-order
    │       │   │   └───supplier-order-details
    │       │   ├───quotation
    │       │   │   ├───create-quotation
    │       │   │   ├───supplier-quotation
    │       │   │   └───supplier-quotation-details
    │       │   └───rfq
    │       │       ├───supplier-rfq
    │       │       └───supplier-rfq-details
    │       └───wefabTeam
    │           ├───manage-suppliers
    │           ├───supplier-finder
    │           ├───wefabTeam-dashboard
    │           └───wefabTeam-layout
    ├───assets
    │   ├───documents
    │   └───scss
    └───environments
PS C:\Users\USER\Desktop\wefab\deployment_trials\Taurus-development> 