name: 'Deploy and Publish Release'

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  deploy-to-ec2:
    name: 'Deploy to EC2'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: 'Deploy to Production'
        run: echo "🚀 Deploying to production..."

  publish-release:
    name: 'Publish GitHub Release'
    needs: deploy-to-ec2
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Release Please to publish'
        uses: googleapis/release-please-action@v4
        with:
        #   command: github-release
          release-type: node # Or simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}