name: 'Propose Release'

on:
  push:
    branches:
      - developer

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: 'Create Release PR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Release Please'
        # THIS IS THE FIX: Use the correct, more modern action
        uses: google-github-actions/release-please-action@v4
        with:
          # Now this 'command' input is valid and will not have a red line
          command: release-pr
          
          release-type: node # Or simple
          
          # The PR will correctly target your 'release' branch
          target-branch: release
          
          # Using your PAT is still the best practice
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}