name: 'Deploy and Release to Production'

on:
  push:
    branches:
      - release

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # YOUR DEPLOY JOB STAYS THE SAME
  deploy:
    name: 'Deploy to Production Server'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Placeholder for Build & Deploy steps'
        run: echo "🚀 Building the Next.js app and deploying to production..."
        # ---
        # IMPORTANT: REPLACE THIS WITH YOUR REAL DEPLOYMENT STEPS
        # ---

  # THIS IS THE NEW JOB YOU SHOULD PASTE IN
  create-release:
    name: 'Create v1.0.0 Release'
    needs: deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Generate changelog'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fromTag: ${{ github.sha }}
          toTag: ${{ github.sha }}
      
      - name: 'Create GitHub Release v1.0.0'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
