name: 'Deploy and Release to Production'

on:
  pull_request:
    branches:
      - release
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:

  deploy:
    name: 'Deploy to Production Server'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    outputs:
      deploy_succeeded: ${{ steps.deploy-status.outputs.success }}

    steps:
      - name: 'Checkout latest code'
        uses: actions/checkout@v4

      - name: 'Run deployment steps'
        id: deploy-status
        run: |
          echo "🚀 Deploying to production..."
          # Simulate deployment
          echo "success=true" >> $GITHUB_OUTPUT

  release:
    name: 'Create GitHub Release'
    needs: deploy
    if: ${{ needs.deploy.outputs.deploy_succeeded == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: 'Run Release Please'
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          command: release
