# .github/workflows/release-please.yml
name: 'Release Please PR Bot'

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: 'Run Release Please'
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Release Please Action'
        uses: google-github-actions/release-please-action@v4
        with:
          # ADD THIS LINE:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

          # The rest of your configuration:
          target-branch: release
          release-type: node
          pull-request-title-pattern: 'chore(release): release ${version}'