# FINAL CORRECTED WORKFLOW
name: Release Please

on:
  push:
    branches: [ release ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # This explicitly tells the action which branch to create the Release PR against.
          target-branch: release
          release-type: node