name: Deploy and Release on Merge

on:
  pull_request:
    branches: [release]
    types: [closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_and_release:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'release' &&
      github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Production Server
        run: |
          echo "🚀 Deploying latest code from the 'release' branch..."
          echo "✅ Deployment successful!"

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: release
          release-type: simple
          skip-github-pull-request: true

      - name: Output Release Information
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "🎉 New release created!"
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "URL: ${{ steps.release.outputs.html_url }}"