name: 'Deploy and Release to Production'

on:
  push:
    branches:
      - release # This workflow runs ONLY when you push or merge to the 'release' branch

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # This job is a placeholder for your actual deployment.
  # Replace the 'run' command with your real build and deploy steps.
  deploy:
    name: 'Deploy to Production Server'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Placeholder for Build & Deploy steps'
        run: echo "🚀 Building the Next.js app and deploying to production..."
        # ---
        # IMPORTANT: REPLACE THE LINE ABOVE WITH YOUR REAL DEPLOYMENT STEPS
        # e.g., setup node, npm ci, npm run build, scp files, ssh restart server...
        # ---

  # This job will create the Git Tag and Release Notes
  create-release:
    name: 'Create Git Tag and Release Notes'
    needs: deploy # This job only runs if the 'deploy' job succeeds
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history for version calculation

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Run semantic-release'
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}